start /b main.py 7_games_per_round_100_pop_size_01 -LOSEFITNESS 0 -LOSEFITNESSGHOST 0
start /b main.py 7_games_per_round_100_pop_size_02 -LOSEFITNESS -0.4 -LOSEFITNESSGHOST -0.6
start /b main.py 7_games_per_round_100_pop_size_03 -LOSEFITNESS -0.4 -LOSEFITNESSGHOST -1
start /b main.py 7_games_per_round_100_pop_size_04 -LOSEFITNESS -0.6 -LOSEFITNESSGHOST -1
start /b main.py 7_games_per_round_100_pop_size_05 -LOSEFITNESS -1 -LOSEFITNESSGHOST -2
start /b main.py 7_games_per_round_100_pop_size_06 -LOSEFITNESS -2 -LOSEFITNESSGHOST -4
start /b main.py 7_games_per_round_100_pop_size_07 -LOSEFITNESS -2 -LOSEFITNESSGHOST -3
start /b main.py 7_games_per_round_100_pop_size_08 -LOSEFITNESS -5 -LOSEFITNESSGHOST -10
start /b main.py 7_games_per_round_100_pop_size_09 -LOSEFITNESS -1 -LOSEFITNESSGHOST -1
start /b main.py 7_games_per_round_100_pop_size_10 -LOSEFITNESS -0.4 -LOSEFITNESSGHOST -0.1
